# Generated by Django 5.1.7 on 2025-04-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
    ]
